package me.fierioziy.api;

import org.bukkit.Location;
import org.bukkit.entity.Player;

/**
 * <p>Interface used to handle packet sending.</p>
 *
 * <p>It provides a non-reflective methods that uses NMS <code>PlayerConnection</code>
 * to send Minecraft packets.</p>
 *
 * <p>It is dynamically generated by <code>ParticleNativeAPI</code> instance and should
 * only be obtained from there.</p>
 * @see me.fierioziy.ParticleNativeAPI
 */
public interface ServerConnection {

    /**
     * <p>Creates a non-reflective wrapper of
     * parameter player's NMS <code>PlayerConnection</code> instance.</p>
     *
     * <p>A generated code for this method looks roughly like this:</p>
     * <pre>{@code
     * PlayerConnection createPlayerConnection(Player player) {
     *     return new PlayerConnection_Impl(player);
     * }
     * }</pre>
     *
     * <p>If you plan to send more than 4-5 packets to one
     * of Players somewhere, then using this wrapper will be
     * more beneficial (faster) than using <code>ServerConnection</code> due
     * to caching NMS PlayerConnection directly in field.</p>
     *
     * <p>It is better <b>not to</b> cache it long-term and any complications to do it
     * anyways <b>will be</b> significantly slower than <code>ServerConnection</code>.</p>
     *
     * @param player a player from which <code>PlayerConnection</code> should be obtained.
     * @return a non-reflective <code>PlayerConnection</code> wrapper of
     * this player's NMS <code>PlayerConnection</code>.
     * @see PlayerConnection
     */
    PlayerConnection createPlayerConnection(Player player);

    /**
     * <p>Sends packet to a Player using its NMS <code>PlayerConnection</code>.</p>
     *
     * <p>A generated code for this method looks roughly like this:</p>
     * <pre>{@code
     * void sendPacket(Player player, Object packet) {
     *     ((CraftPlayer) player).getHandle().playerConnection
     *             .sendPacket((Packet) packet);
     * }
     * }</pre>
     *
     * <p>A packet parameter must be an instance of Minecraft packet interface.
     * Otherwise, you might get <code>ClassCastException</code> on packet parameter.</p>
     *
     * <p>You can use this method to send other packet than instances created using
     * this API. Any valid Minecraft packet can be used by this method.</p>
     *
     * @param player a player to which send a packet object.
     * @param packet a valid Minecraft packet created either by this API or
     *               via reflections.
     * @throws ClassCastException when provided packet object is not
     * an instance of Minecraft packet interface.
     */
    void sendPacket(Player player, Object packet);

    /**
     * <p>Send a packet to every player in given radius.</p>
     *
     * <p>Technically speaking, gets all players around loc parameter
     * in given radius and send packet to every player in radius
     * using its NMS <code>PlayerConnection</code>.</p>
     *
     * <p>A generated code for this method looks (roughly) like this:</p>
     * <pre>{@code
     * void sendPacket(Location loc, double radius, Object packet) {
     *     radius *= radius;
     *     Packet nmsPacket = (Packet) packet;
     *
     *     double x = loc.getX();
     *     double y = loc.getY();
     *     double z = loc.getZ();
     *
     *     // this initializations are optimized
     *     int length = loc.getWorld().getPlayers().size();
     *     Iterator it = loc.getWorld().getPlayers().iterator();
     *
     *     for (int i = 0; i < length; ++i) {
     *         CraftPlayer p = (CraftPlayer) it.next();
     *         Location pLoc = p.getLocation();
     *
     *         // pseudo code if statement is optimized
     *         if (( (pLoc.getX() - x)^2
     *             + (pLoc.getY() - y)^2
     *             + (pLoc.getZ() - z)^2) <= radius) {
     *             p.getHandle().playerConnection.sendPacket(nmsPacket);
     *         }
     *     }
     * }
     * }</pre>
     *
     * <p>This method should be a little faster than normal for-each loop
     * with radius check due to few bytecode optimizations:</p>
     * <ul>
     *     <li>one packet cast per entire loop,</li>
     *     <li>duplicating list reference around
     *     <code>length</code> and <code>it</code> variables,</li>
     *     <li>duplicating subtraction results around radius check,</li>
     *     <li>using traditional <code>for</code> loop with
     *     cached list size instead of <code>hasNext</code> interface
     *     method check on each iteration.</li>
     * </ul>
     *
     * <p>A packet parameter must be an instance of Minecraft packet interface.
     * Otherwise, you might get <code>ClassCastException</code> on packet parameter.</p>
     *
     * <p>You can use this method to send other packet than instances created using
     * this API. Any valid Minecraft packet can be used by this method.</p>
     *
     * @param loc a <code>Location</code> containing position.
     * @param radius a spherical radius around which send packet to
     *               nearby players.
     * @param packet a valid Minecraft packet created either by this API or
     *               via reflections.
     * @throws ClassCastException when provided packet object is not
     * an instance of Minecraft packet interface.
     */
    void sendPacket(Location loc, double radius, Object packet);
}
