package me.fierioziy.api;

import org.bukkit.entity.Player;

/**
 * <p>Interface used to handle packet sending.</p>
 *
 * <p>It provides a non-reflective methods that uses NMS <code>PlayerConnection</code>
 * to send Minecraft packets.</p>
 *
 * <p>It is dynamically generated by <code>ParticleNativeAPI</code> instance and should
 * only be obtained from there.</p>
 * @see me.fierioziy.ParticleNativeAPI
 */
public interface ServerConnection {

    /**
     * <p>Creates a non-reflective wrapper of
     * parameter player's NMS <code>PlayerConnection</code> instance.</p>
     *
     * <p>A generated code for this method looks roughly like this:</p>
     * <pre>{@code
     * PlayerConnection createPlayerConnection(Player player) {
     *     return new PlayerConnection_Impl(player);
     * }
     * }</pre>
     *
     * @param player a player from which <code>PlayerConnection</code> should be obtained.
     * @return a non-reflective <code>PlayerConnection</code> wrapper of
     * this player's NMS <code>PlayerConnection</code>.
     * @see PlayerConnection
     */
    PlayerConnection createPlayerConnection(Player player);

    /**
     * <p>Obtains a NMS <code>PlayerConnection</code> from player parameter
     * and invokes sendPacket on it with packet parameter.</p>
     *
     * <p>A generated code for this method looks roughly like this:</p>
     * <pre>{@code
     * void sendPacket(Player player, Object packet) {
     *     ((CraftPlayer) player).getHandle().playerConnection
     *             .sendPacket((Packet) packet);
     * }
     * }</pre>
     *
     * <p>A packet parameter must be an instance of Minecraft packet interface.
     * Otherwise, you might get <code>ClassCastException</code> on packet parameter.</p>
     *
     * <p>You can use this method to send other packet than instances created using
     * this API. Any valid Minecraft packet can be used by this method.</p>
     *
     * @param player a player to which send a packet object.
     * @param packet a valid Minecraft packet created either by this API or
     *               via reflections.
     * @throws ClassCastException when provided packet object is not
     * an instance of Minecraft packet interface.
     */
    void sendPacket(Player player, Object packet);
}
